server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/setecdemo
    username: postgres
    password: 123@#!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.web: DEBUG



